#  -------------------------------------------------------------------------
#  Copyright (C) 2023 BMW AG
#  -------------------------------------------------------------------------
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#  -------------------------------------------------------------------------

# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

---
version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.10"

sphinx:
    configuration: doc/conf.py
    fail_on_warning: true

python:
    install:
        - requirements: doc/requirements.txt
...
