#ifndef PROGRAMDEFINE_H
#define PROGRAMDEFINE_H
#include <QString>
#include <QStringLiteral>
#include <string>

#define JSON_X                      ("x")
#define JSON_Y                      ("y")
#define JSON_Z                      ("z")
#define JSON_W                      ("w")
#define JSON_LAST_OBJECT_ID         ("lastObjectId")
#define JSON_UNIFORM                ("Uniform")
#define JSON_NODE                   ("node")
#define JSON_ACTIVE_NODE            ("active_node")
#define JSON_CHILD                  ("child")
#define JSON_NAME                   ("name")
#define JSON_OBJECTID               ("objectId")
#define JSON_TRANSLATION            ("translation")
#define JSON_ROTATION               ("rotation")
#define JSON_SCALE                  ("scaling")
#define JSON_BASIC_PROPERTY         ("basicProperty")
#define JSON_KEYFRAME               ("keyFrame")
#define JSON_TYPE                   ("type")
#define JSON_MATERIAL               ("material")
#define JSON_MESH                   ("mesh")
#define JSON_CUSTOM_PROPERTY        ("customProperty")
#define JSON_PROPERTY               ("property")
#define JSON_CURVE                  ("curve")
#define JSON_SAMPLEPROPERTY         ("sampleProperty")
#define JSON_CURVEBINDING           ("curveBinding")
#define JSON_SYSTEMPROPERTY         ("systemProperty")
#define JSON_ANIMATIONPROPERTY      ("animationProperty")
#define JSON_DATA_TYPE              ("dataType")
#define JSON_DATA                   ("Data")
#define JSON_INTERPOLATION_TYPE     ("InterpolationType")
#define JSON_LEFT_TANGENT           ("LeftTangent")
#define JSON_RIGHT_TANGENT          ("RightTangent")
#define JSON_LEFT_KEYFRAME          ("LeftKeyFrame")
#define JSON_RIGHT_KEYFRAME         ("RightKeyFrame")
#define JSON_LEFT_DATA              ("LeftData")
#define JSON_RIGHT_DATA             ("RightData")
#define JSON_POINT_LIST             ("pointList")
#define JSON_START_TIME             ("start")
#define JSON_END_TIME               ("end")
#define JSON_LOOP_COUNT             ("loopCount")
#define JSON_UPDATE_INTERVAL        ("updateInterval")
#define JSON_VALUE                  ("value")
#define JSON_ANIMATION              ("animation")
#define JSON_ACTIVE_ANIMATION       ("active_animation")
#define JSON_MATRX_OO               ("m00")
#define JSON_MATRX_O1               ("m01")
#define JSON_MATRX_O2               ("m02")
#define JSON_MATRX_O3               ("m03")
#define JSON_MATRX_10               ("m10")
#define JSON_MATRX_11               ("m11")
#define JSON_MATRX_12               ("m12")
#define JSON_MATRX_13               ("m13")
#define JSON_MATRX_20               ("m20")
#define JSON_MATRX_21               ("m21")
#define JSON_MATRX_22               ("m22")
#define JSON_MATRX_23               ("m23")
#define JSON_MATRX_30               ("m30")
#define JSON_MATRX_31               ("m31")
#define JSON_MATRX_32               ("m32")
#define JSON_MATRX_33               ("m33")
#define JSON_RENDER_MODE            ("renderMode")
#define JSON_WINDING                ("winding")
#define JSON_CULLING                ("culling")
#define JSON_BLENDING               ("blending")
#define JSON_BLEND_OPT_COLOR        ("blendOpreationColor")
#define JSON_BLEND_OPT_ALPHA        ("blendOpreationAlpha")
#define JSON_SRC_COLOR_FACTOR       ("sourceColorFactor")
#define JSON_SRC_ALPHA_FACTOR       ("sourceAlphaFactor")
#define JSON_DEST_COLOR_FACTOR      ("destinationColorFactor")
#define JSON_DEST_ALPHA_FACTOR      ("destinationAlphaFactor")
#define JSON_DEPTH_COMPARE          ("depthCompare")
#define JSON_DEPTH_WRITE            ("depthWrite")
#define JSON_COLOR_WRITE            ("colorWrite")
#define JSON_RED                    ("red")
#define JSON_GREEN                  ("green")
#define JSON_BLUE                   ("blue")
#define JSON_ALPHA                  ("alpha")
#define JSON_SHADER_REFERENCE       ("shaderReference")
#define JSON_BITMAP_REFERENCE       ("bitmapReference")
#define JSON_MIN_FILTER             ("minFliter")
#define JSON_MAG_FILTER             ("magFliter")
#define JSON_ANISOTROPIC_SAMPLES    ("anisotropicSamples")
#define JSON_WRAPE_MODEU            ("wrapeModeU")
#define JSON_WRAPE_MODEV            ("wrapeModeV")
#define JSON_UNIFORM_NAME           ("uniformName")
#define JSON_TEXTURE                ("texture")
#define JSON_FLOAT                  ("Float")
#define JSON_INT                    ("Int")
#define JSON_BOOL                   ("Bool")
#define JSON_STRING                 ("String")
#define JSON_SHADER                 ("shader")
#define JSON_VERTEX_SHADER          ("vertexShader")
#define JSON_FRAGMENT_SHADER        ("fragmentShader")
#define JSON_BITMAP                 ("bitmap")
#define JSON_RESOURCE               ("resource")
#define JSON_GENERATE_MIPMAPS       ("generateMipMaps")
#define JSON_MATERIAL_REF			("materialReference")
#define PTX_SCENE_NAME				QString("Scene")
#define PTW_USED_ANIMATION_NAME		std::string("UsedAnimationName")
#define PTW_PRE_CURVES_ONE_PROP		std::string("Multi-CurvesSingleProp-")
#define PTW_PRE_ANIMATS_ONE_CURVE   std::string("Multi-AnimationsSingleCurve-")
#define PTW_SUF_ANIMAT_DOMAIN	    std::string("_domain")
#define PTW_SUF_CURVE_INETERAL		std::string("_interal")
#define PTW_SCALE_DIVIDE_VALUE		std::string("ScaleDivideValue.outputX")
#define PTW_SCALE_DIVIDE_MIRROR		std::string("ScaleDivideValue.outputX.Mirror")
#define PTW_SCALE_DIV_MUL_VALUE		std::string("ScaleDivResultMulValue.outputX")
#define PTW_FRAG_SYS_OPACITY		std::string("Sys_Opacity")
#define PTW_FRAG_SYS_DOT_OPACITY	std::string("Sys_DotOpacity")
#define PTW_FRAG_SYS_DOT_SIZE		std::string("Sys_DotSize")
#define PTW_FRAG_SYS				std::string("Sys_")


#define PTW_SINGLE_AN_INTERVAL		std::string("Animation_domain")

// externalModelValue
#define PTW_EX_HUD_NAME				std::string("HUD")
#define PTW_EX_CON_IPA_ICON_C		std::string("Content_IPAIconTransformation_C")
#define PTW_EX_HUD_CON_IPA_ICON_C	std::string("HUD_Content_IPAIconTransformation_C")
#define PTW_EX_TRIGGLE_ANIMATION	std::string("Animation")
#define PTW_EX_RIGHT_MIRROR			std::string("Right")

// Sys
#define PTW_EX_SCALE_NAME			std::string("Scale")
#define PTW_EX_OPACITY_NAME			std::string("Opacity")
#define PTW_EX_DOT_OPACITY			std::string("DotOpacity")
#define PTW_EX_DOT_SIZE				std::string("DotSize")

// internalModelValue
#define PTW_IN_V4					std::string("_V4")
#define PTW_IN_COLOR_MODE			std::string("colorMode_color")
#define PTW_IN_U_COLOR				std::string("u_color")

// projectName
#define PRO_ELLIE					std::string("Ellie")
#define PRO_GASSTATION				std::string("GasStation")


#define PI (3.14159265358979323846)
#endif // PROGRAMDEFINE_H
